# Generated by Django 5.1.7 on 2025-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_employe',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$oMuWAVDxfE6Wkrj8AR2i5p$+2w4AvBUWd4XMoAsstC9ouUzGjh2Awz3NotikQK1t0w=', max_length=128, verbose_name='Хэш пароля'),
        ),
    ]
